### ISSUE TITLE
python error when trying to open configtool.py

### ISSUE THREAD

**Issue by rallekralle11** [Traumflug/Teacup_Firmware#317] opened 2018-12-20 10:58 UTC
Traceback (most recent call last):

File "configtool.py", line 185, in <module>

StartGui(getSettings())

File "F:\Teacup_Firmware-master\configtool\gui.py", line 615, in StartGui

frame = ConfigFrame(settings)

File "F:\Teacup_Firmware-master\configtool\gui.py", line 72, in __init__

self.pgPrinter = PrinterPanel(self, self.nb, self.settings)

File "F:\Teacup_Firmware-master\configtool\printerpanel.py", line 47, in __init__

self.pgMech = self.registerPage(MechanicalPage, "Mechanical")

File "F:\Teacup_Firmware-master\configtool\printerpanel.py", line 59, in registerPage

font = self.settings.font, **kwargs)

File "F:\Teacup_Firmware-master\configtool\mechanicalpage.py", line 65, in __init__

sz.AddSpacer((10, 10), pos = (0, 0))

TypeError: Sizer.AddSpacer(): argument 1 has unexpected type 'tuple'

**Comment by Wurstnase** [comment] 2018-12-21 19:01
Duplicate of https://github.com/Traumflug/Teacup_Firmware/issues/281

**Closed by Wurstnase** 2018-12-21 19:01 UTC
